adjust makefiles

diff --git a/examples/jackd-listener/avb-xdp/Makefile b/examples/jackd-listener/avb-xdp/Makefile
--- a/examples/jackd-listener/avb-xdp/Makefile
+++ b/examples/jackd-listener/avb-xdp/Makefile
@@ -1,11 +1,100 @@
 # SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)
 
-
-XDP_TARGETS  := af_xdp_kern
-USER_TARGETS := af_xdp_user
+# Departing from the implicit _user.c scheme
+XDP_TARGETS  := xdp_avb_kern
+USER_TARGETS := xdp_load_and_stats
 
 LIBBPF_DIR = ../libbpf/src/
-COMMON_DIR = ../common/
+COMMON_DIR_BPF = ../common/
 
-include $(COMMON_DIR)/common.mk
-LIBS += -lpthread
+LLC ?= llc
+CLANG ?= clang
+CC ?= gcc
+
+XDP_C = ${XDP_TARGETS:=.c}
+XDP_OBJ = ${XDP_C:.c=.o}
+USER_C := ${USER_TARGETS:=.c}
+USER_OBJ := ${USER_C:.c=.o}
+
+OBJECT_LIBBPF = $(LIBBPF_DIR)/libbpf.a
+
+# Extend if including Makefile already added some
+COMMON_OBJS_BPF += $(COMMON_DIR_BPF)/common_params.o $(COMMON_DIR_BPF)/common_user_bpf_xdp.o
+
+# Create expansions for dependencies
+COMMON_H_BPF := ${COMMON_OBJS_BPF:.o=.h}
+
+EXTRA_DEPS +=
+
+# BPF-prog kern and userspace shares struct via header file:
+KERN_USER_H ?= $(wildcard common_kern_user.h)
+
+CFLAGS ?= -I$(LIBBPF_DIR)/build/usr/include/ -g
+# Extra include for Ubuntu issue #44
+CFLAGS += -I/usr/include/x86_64-linux-gnu
+CFLAGS += -I../headers/
+LDFLAGS ?= -L$(LIBBPF_DIR)
+
+LIBS = -l:libbpf.a -lelf $(USER_LIBS)
+
+all: llvm-check $(USER_TARGETS) $(XDP_OBJ)
+
+.PHONY: clean $(CLANG) $(LLC)
+
+clean:
+	rm -rf $(LIBBPF_DIR)/build
+	$(MAKE) -C $(LIBBPF_DIR) clean
+	$(MAKE) -C $(COMMON_DIR_BPF) clean
+	rm -f $(USER_TARGETS) $(XDP_OBJ) $(USER_OBJ)
+	rm -f *.ll
+	rm -f *~
+
+# For build dependency on this file, if it gets updated
+COMMON_MK_BPF = $(COMMON_DIR_BPF)/common.mk
+
+llvm-check: $(CLANG) $(LLC)
+	@for TOOL in $^ ; do \
+		if [ ! $$(command -v $${TOOL} 2>/dev/null) ]; then \
+			echo "*** ERROR: Cannot find tool $${TOOL}" ;\
+			exit 1; \
+		else true; fi; \
+	done
+
+$(OBJECT_LIBBPF):
+	@if [ ! -d $(LIBBPF_DIR) ]; then \
+		echo "Error: Need libbpf submodule"; \
+		echo "May need to run git submodule update --init"; \
+		exit 1; \
+	else \
+		cd $(LIBBPF_DIR) && $(MAKE) all; \
+		mkdir -p build; DESTDIR=build $(MAKE) install_headers; \
+	fi
+
+# Create dependency: detect if C-file change and touch H-file, to trigger
+# target $(COMMON_OBJS_BPF)
+$(COMMON_H_BPF): %.h: %.c
+	touch $@
+
+# Detect if any of common obj changed and create dependency on .h-files
+$(COMMON_OBJS_BPF): %.o: %.h
+	make -C $(COMMON_DIR_BPF)
+
+$(USER_TARGETS): %: %.c  $(OBJECT_LIBBPF) Makefile $(COMMON_MK_BPF) $(COMMON_OBJS_BPF) $(KERN_USER_H) $(EXTRA_DEPS)
+	$(CC) -Wall $(CFLAGS) $(LDFLAGS) -o $@ $(COMMON_OBJS_BPF) \
+	 $< $(LIBS)
+
+$(XDP_OBJ): %.o: %.c  Makefile $(COMMON_MK_BPF) $(KERN_USER_H) $(EXTRA_DEPS)
+	$(CLANG) -S \
+	    -target bpf \
+	    -D __BPF_TRACING__ \
+	    $(CFLAGS) \
+	    -Wall \
+	    -Wno-unused-value \
+	    -Wno-pointer-sign \
+	    -Wno-compare-distinct-pointer-types \
+	    -Werror \
+	    -O2 -emit-llvm -c -g -o ${@:.o=.ll} $<
+	$(LLC) -march=bpf -filetype=obj -o $@ ${@:.o=.ll}
+
+
+
